services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.1-alpine3.18"
    environment:
      POSTGRES_PASSWORD: "local_password"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"

  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"
